# Generated by Django 4.0.5 on 2023-02-07 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_subscription_cancel_date_subscription_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='plan',
            field=models.CharField(choices=[('FREE', 'Free'), ('INDIVIDUAL', 'Individual'), ('BUSINESS', 'Business')], default='FREE', max_length=100),
        ),
    ]
