# Generated by Django 4.0.5 on 2023-03-02 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_alter_subscription_plan'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='subscription',
            managers=[
            ],
        ),
    ]
