# Generated by Django 4.0.5 on 2023-03-03 14:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_alter_subscription_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Webhook',
            fields=[
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='date updated')),
                ('key', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'webhook',
            },
        ),
    ]
