# Generated by Django 4.0.5 on 2023-03-06 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_webhook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('DOWNGRADED', 'Downgraded'), ('CANCELED', 'Canceled')], default='ACTIVE', max_length=100),
        ),
    ]
