# Generated by Django 4.0.5 on 2023-05-16 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_alter_subscription_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='plan',
            field=models.CharField(choices=[('FREE', 'Free'), ('STARTER', 'Starter'), ('INDIVIDUAL', 'Individual'), ('BUSINESS', 'Business')], default='FREE', max_length=100),
        ),
    ]
