# Generated by Django 4.0.5 on 2023-05-29 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_alter_subscription_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('DOWNGRADED', 'Downgraded'), ('UPGRADED', 'Upgraded'), ('CANCELED', 'Canceled')], default='ACTIVE', max_length=100),
        ),
    ]
