# Generated by Django 4.0.5 on 2023-01-19 18:13

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('languages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Website',
            fields=[
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='date updated')),
                ('serve_sync_status', models.CharField(choices=[('PENDING', 'Pending'), ('SYNCING', 'Syncing'), ('FAILED', 'Failed'), ('UPDATED', 'Updated')], default='PENDING', max_length=100)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='website', to='projects.project')),
            ],
            options={
                'db_table': 'website',
            },
        ),
        migrations.CreateModel(
            name='WebsiteLangVersion',
            fields=[
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='date updated')),
                ('subfolder', models.SlugField(max_length=200)),
                ('serve_sync_status', models.CharField(default='PENDING', max_length=100)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='languages', to='languages.language')),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='websites.website')),
            ],
            options={
                'db_table': 'website_lang_version',
                'unique_together': {('website', 'language')},
            },
        ),
    ]
