# Generated by Django 4.0.5 on 2023-02-03 09:03

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0002_alter_website_managers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteDomain',
            fields=[
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='date updated')),
                ('domain', models.CharField(max_length=2000)),
                ('serve_in_www', models.BooleanField(default=True)),
                ('verified', models.BooleanField(default=False)),
                ('domain_type', models.CharField(choices=[('DEFAULT_SUBDOMAIN', 'Default Subdomain'), ('CUSTOM_ADDED', 'Custom Added')], default='CUSTOM_ADDED', max_length=100)),
                ('serve_sync_status', models.CharField(choices=[('PENDING', 'Pending'), ('SYNCING', 'Syncing'), ('FAILED', 'Failed'), ('UPDATED', 'Updated')], default='PENDING', max_length=100)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='websites.website')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
