# Generated by Django 4.0.5 on 2023-03-02 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0003_websitedomain'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='website',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='websitedomain',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='websitelangversion',
            managers=[
            ],
        ),
    ]
