# Generated by Django 4.0.5 on 2023-03-06 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0004_alter_website_managers_alter_websitedomain_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitelangversion',
            name='is_disabled',
            field=models.BooleanField(default=False),
        ),
    ]
