# Generated by Django 4.0.5 on 2023-03-29 20:16

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0005_websitelangversion_is_disabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteSettings',
            fields=[
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='date updated')),
                ('show_badge', models.BooleanField(default=False)),
                ('serve_sync_status', models.CharField(default='PENDING', max_length=100)),
                ('website', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='websites.website')),
            ],
            options={
                'ordering': ('-date_created',),
            },
        ),
    ]
