# Generated by Django 4.0.5 on 2023-04-11 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0006_websitesettings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='websitesettings',
            options={},
        ),
    ]
