# Generated by Django 4.0.5 on 2023-01-19 18:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='date updated')),
                ('name', models.CharField(max_length=256)),
                ('code', models.CharField(max_length=3)),
                ('emoji', models.CharField(blank=True, max_length=20, null=True)),
                ('image', models.CharField(blank=True, max_length=500, null=True)),
                ('available', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'language',
            },
        ),
    ]
