# Generated by Django 4.0.5 on 2023-01-23 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0002_alter_language_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='code',
            field=models.CharField(max_length=8),
        ),
    ]
