# Generated by Django 4.0.5 on 2023-03-02 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0003_alter_language_code'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='language',
            managers=[
            ],
        ),
    ]
