# Generated by Django 4.0.5 on 2023-06-07 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0004_alter_language_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='translation_code',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
