# Generated by Django 4.0.5 on 2023-08-15 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0005_language_translation_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='local_name',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
