# Generated by Django 4.0.5 on 2023-01-24 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_usercredits_managers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usercredits',
            options={'verbose_name_plural': 'User Credits'},
        ),
    ]
