# Generated by Django 4.0.5 on 2023-01-27 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_usercredits_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercredits',
            name='source',
            field=models.CharField(blank=True, choices=[('MANUALLY', 'Manually'), ('SUBSCRIPTION', 'Subscription'), ('CREDITS', 'Credits')], max_length=50, null=True),
        ),
    ]
