# Generated by Django 4.0.5 on 2023-04-12 14:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_userfirebasetoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfirebasetoken',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='firebase', to=settings.AUTH_USER_MODEL),
        ),
    ]
