# Generated by Django 4.0.5 on 2023-05-31 12:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0008_alter_userfirebasetoken_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='guid',
            field=models.UUIDField(default=uuid.uuid4, null=True),
        ),
    ]
