# Generated by Django 4.0.5 on 2023-05-31 12:49

from django.db import migrations
import uuid


def gen_uuid(apps, schema_editor):
    MyModel = apps.get_model("users", "user")
    for row in MyModel.objects.all():
        row.guid = uuid.uuid4()
        row.save(update_fields=["guid"])


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0009_add_user_guid_field'),
    ]

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
