# Generated by Django 4.0.5 on 2023-05-31 12:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0010_populate_guid_values'),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="guid",
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
