# Generated by Django 4.0.5 on 2023-01-19 18:13

from django.db import migrations, models
import django.db.models.deletion
import projects.utils
import projects.validators
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IgnoreProjectClass',
            fields=[
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='date updated')),
                ('class_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'ignore_project_class',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='date updated')),
                ('name', models.CharField(max_length=200)),
                ('domain', models.CharField(max_length=2000)),
                ('image', models.FileField(blank=True, null=True, upload_to='')),
                ('serve_in_www', models.BooleanField(default=True)),
                ('verified', models.BooleanField(default=False)),
                ('archived', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'project',
            },
        ),
        migrations.CreateModel(
            name='ProjectMedia',
            fields=[
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='date updated')),
                ('media_file', models.FileField(upload_to=projects.utils.get_file_upload_path, validators=[projects.validators.validate_file])),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medias', to='projects.project')),
            ],
            options={
                'db_table': 'project_media',
            },
        ),
    ]
