# Generated by Django 4.0.5 on 2023-01-19 18:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('languages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='main_language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_language', to='languages.language'),
        ),
        migrations.AddField(
            model_name='ignoreprojectclass',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ignore_project_classes', to='projects.project'),
        ),
        migrations.AlterUniqueTogether(
            name='project',
            unique_together={('name', 'domain', 'created_by')},
        ),
        migrations.AlterUniqueTogether(
            name='ignoreprojectclass',
            unique_together={('project', 'class_name')},
        ),
    ]
