# Generated by Django 4.0.5 on 2023-01-19 19:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0003_alter_ignoreprojectclass_managers_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='project',
            unique_together={('name', 'domain', 'created_by', 'deleted_at', 'is_deleted')},
        ),
    ]
