# Generated by Django 4.0.5 on 2023-03-02 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_projectverificationidentifier'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='ignoreprojectclass',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='project',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='projectmedia',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='projectverificationidentifier',
            managers=[
            ],
        ),
    ]
