# Generated by Django 4.0.5 on 2023-03-06 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_alter_ignoreprojectclass_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_disabled',
            field=models.BooleanField(default=False),
        ),
    ]
