# Generated by Django 4.0.5 on 2023-06-22 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_project_is_disabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='platform',
            field=models.CharField(choices=[('WEBFLOW', 'Webflow'), ('FRAMER', 'Framer')], default='WEBFLOW', max_length=100),
        ),
    ]
