# Generated by Django 4.0.5 on 2023-09-04 15:35

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_project_platform'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectDisableWordTranslation',
            fields=[
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='date updated')),
                ('word', models.CharField(max_length=100)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disable_translations', to='projects.project')),
            ],
            options={
                'db_table': 'project_disable_word_translation',
                'unique_together': {('project', 'word')},
            },
        ),
    ]
