# Generated by Django 4.0.5 on 2023-06-09 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0002_alter_maintenancemode_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancemode',
            name='expected_down_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
