# Generated by Django 4.0.5 on 2023-01-19 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('websites', '0001_initial'),
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagelangversion',
            name='website_lang_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='websites.websitelangversion'),
        ),
        migrations.AddField(
            model_name='page',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='websites.website'),
        ),
        migrations.AlterUniqueTogether(
            name='pagelangversion',
            unique_together={('page', 'website_lang_version', 'custom_page_url')},
        ),
        migrations.AlterUniqueTogether(
            name='page',
            unique_together={('website', 'page_url')},
        ),
    ]
