# Generated by Django 4.0.5 on 2023-01-19 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0002_alter_website_managers_and_more'),
        ('pages', '0003_alter_page_managers_alter_pagelangversion_managers_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='page',
            unique_together={('website', 'page_url', 'deleted_at', 'is_deleted')},
        ),
        migrations.AlterUniqueTogether(
            name='pagelangversion',
            unique_together={('page', 'website_lang_version', 'custom_page_url', 'deleted_at', 'is_deleted')},
        ),
    ]
