# Generated by Django 4.0.5 on 2023-02-03 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0003_websitedomain'),
        ('pages', '0004_alter_page_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publishedpageversion',
            name='domain',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='websites.websitedomain'),
        ),
    ]
