# Generated by Django 4.0.5 on 2023-03-02 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_publishedpageversion_domain'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='page',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='pagelangversion',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='parsedpage',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='publishedpageversion',
            managers=[
            ],
        ),
    ]
