# Generated by Django 4.0.5 on 2023-04-11 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_alter_page_managers_alter_pagelangversion_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('LINK_NOT_FOUND', 'Link Not Found'), ('PAGE_NOT_FOUND', 'Page Not Found')], default='ACTIVE', max_length=100),
        ),
    ]
