# Generated by Django 4.0.5 on 2023-07-18 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0007_alter_websitesettings_options'),
        ('pages', '0007_page_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PublishedPageVersion',
            new_name='PublishedPageVersionStatus',
        ),
        migrations.AlterModelTable(
            name='publishedpageversionstatus',
            table='published_page_version_status',
        ),
    ]
