# Generated by Django 4.0.5 on 2023-07-18 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_rename_publishedpageversion_publishedpageversionstatus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publishedpageversionstatus',
            name='status',
            field=models.CharField(choices=[('PUBLISHED', 'Published'), ('UNPUBLISHED', 'Unpublished')], default='PUBLISHED', max_length=100),
        ),
    ]
