# Generated by Django 4.0.5 on 2023-09-01 07:05

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_project_platform'),
        ('websites', '0007_alter_websitesettings_options'),
        ('pages', '0010_add_page_version_specific_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageVersionCustomCode',
            fields=[
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='date updated')),
                ('head_code', models.CharField(blank=True, max_length=250, null=True)),
                ('body_code', models.CharField(blank=True, max_length=250, null=True)),
                ('page_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_codes', to='pages.pagelangversion')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_codes', to='projects.project')),
                ('website_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_codes', to='websites.websitelangversion')),
            ],
            options={
                'db_table': 'page_version_custom_code',
            },
        ),
        migrations.DeleteModel(
            name='PageVersionSpecificCode',
        ),
    ]
