"""
Django settings for app project.

Generated by 'django-admin startproject' using Django 3.2.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""


import os
import environ
from datetime import timedelta
from pathlib import Path
from google.cloud.logging import Client
from app.consts import DEV_ENVIRONMENT, PROD_ENVIRONMENT, LOCAL_ENVIRONMENT


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


ENVIRONMENT = os.environ.get('ENV', '')
if ENVIRONMENT == DEV_ENVIRONMENT:
    print('Dev environment: reading env variables from .env.dev')
    environ.Env.read_env(os.path.join(BASE_DIR, '.env.dev'))
elif ENVIRONMENT == PROD_ENVIRONMENT:
    print('Prod environment: reading env variables from .env.prod')
    environ.Env.read_env(os.path.join(BASE_DIR, '.env.prod'))
elif ENVIRONMENT == LOCAL_ENVIRONMENT:
    print('Local environment: reading env variables from .env.local')
    environ.Env.read_env(os.path.join(BASE_DIR, '.env.local'))
else:
    print('No ENV variable found: reading env variables from .env')
    environ.Env.read_env(os.path.join(BASE_DIR, '.env'))
env = environ.Env()

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-8ae#78x$!066cp#*ibn#2i$4u^ai$r=8l74roni0ud%0@5+cik'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool('DEBUG', False)

ALLOWED_HOSTS = ['*']


# Application definition

DJANGO_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'dj_rest_auth',
    'dj_rest_auth.registration',
]

THIRD_PARTY_APPS = [
    'drf_yasg',
    'corsheaders',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'rest_framework',
    'rest_framework.authtoken',
    'django_extensions',
    'import_export',
]

CUSTOM_APPS = [
    'users',
    'authentication',
    'projects',
    'commons',
    'languages',
    'websites',
    'pages',
    'translations',
    'api',
    'payments',
    'website_redirects',
    'firebase',
]

INSTALLED_APPS = DJANGO_APPS + THIRD_PARTY_APPS + CUSTOM_APPS

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'commons.middleware.MaintenanceModeMiddleware',
]

ROOT_URLCONF = 'app.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'commons/templates', BASE_DIR / 'authentication/templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
            'libraries': {
                'environment_value': 'commons.templatetags.custom_tags',
            },
        },
    },
]

WSGI_APPLICATION = 'app.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles/')
STATICFILES_STORAGE = 'whitenoise.storage.CompressedStaticFilesStorage'

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

SITE_ID = 1

AUTH_USER_MODEL = 'users.User'

ACCOUNT_USER_MODEL_USERNAME_FIELD = None
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_USERNAME_REQUIRED = False
ACCOUNT_AUTHENTICATION_METHOD = 'email'

SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': [
            'profile',
            'email',
        ],
        'AUTH_PARAMS': {
            'access_type': 'offline',
        },
    }
}

AUTHENTICATION_BACKENDS = [
    'allauth.account.auth_backends.AuthenticationBackend',
    'django.contrib.auth.backends.ModelBackend',
]

ACCOUNT_EMAIL_VERIFICATION = 'optional'
ACCOUNT_EMAIL_CONFIRMATION_EXPIRE_DAYS = 14
SOCIALACCOUNT_EMAIL_VERIFICATION = 'mandatory'


ACCOUNT_ADAPTER = 'authentication.adapters.CustomAccountAdapter'
SOCIALACCOUNT_ADAPTER = 'authentication.adapters.CustomSocialAccountAdapter'
ACCOUNT_PASSWORD_RESET_VERIFIED_ONLY = False

MAX_REQUEST_FOR_UNAUTHENTICATED_USERS_PER_MIN = env.str(
    'MAX_REQUEST_FOR_UNAUTHENTICATED_USERS_PER_MIN', 100
)
MAX_REQUEST_FOR_AUTHENTICATED_USERS_PER_MIN = env.str(
    'MAX_REQUEST_FOR_AUTHENTICATED_USERS_PER_MIN', 100
)
MAX_REQUEST_FOR_AUTHENTICATED_USERS_IN_CUSTOM_ACTION_PER_MIN = env.str(
    'MAX_REQUEST_FOR_AUTHENTICATED_USERS_IN_CUSTOM_ACTION_PER_MIN', 5
)

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'dj_rest_auth.jwt_auth.JWTCookieAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.LimitOffsetPagination',
    'PAGE_SIZE': 100,
    'DEFAULT_VERSIONING_CLASS': 'rest_framework.versioning.NamespaceVersioning',
    'DEFAULT_VERSION': 'v1',
    'ALLOWED_VERSIONS': {
        'v1',
    },
    'VERSION_PARAM': 'version',
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': f'{MAX_REQUEST_FOR_UNAUTHENTICATED_USERS_PER_MIN}/min',
        'user': f'{MAX_REQUEST_FOR_AUTHENTICATED_USERS_PER_MIN}/min',
        'custom': f'{MAX_REQUEST_FOR_AUTHENTICATED_USERS_IN_CUSTOM_ACTION_PER_MIN}/min',
    },
}

REST_AUTH_SERIALIZERS = {
    'LOGIN_SERIALIZER': 'authentication.serializers.CustomLoginSerializer',
    'PASSWORD_RESET_SERIALIZER': 'authentication.serializers.CustomPasswordResetSerializer',
    'USER_DETAILS_SERIALIZER': 'users.serializers.CustomUserSerializer',
}

REST_AUTH_REGISTER_SERIALIZERS = {
    'REGISTER_SERIALIZER': 'authentication.serializers.CustomRegisterSerializer',
    'PASSWORD_RESET_SERIALIZER': 'authentication.serializers.CustomPasswordResetSerializer',
}

REST_USE_JWT = True

REST_SESSION_LOGIN = False

JWT_AUTH_COOKIE = 'linguana-auth'
JWT_AUTH_REFRESH_COOKIE = 'linguana-refresh-token'

EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

if env.str('EMAIL_HOST', ''):
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_HOST = env.str('EMAIL_HOST')
    EMAIL_USE_TLS = env.bool('EMAIL_USE_TLS', True)
    EMAIL_USE_SSL = env.bool('EMAIL_USE_SSL', False)
    EMAIL_PORT = env.int('EMAIL_PORT', 587)
    EMAIL_HOST_USER = env.str('EMAIL_HOST_USER', '')
    EMAIL_HOST_PASSWORD = env.str('EMAIL_HOST_PASSWORD', '')
    DEFAULT_FROM_EMAIL = env.str('DEFAULT_FROM_EMAIL', '')


SWAGGER_SETTINGS = {
    'USE_SESSION_AUTH': False,
    'SECURITY_DEFINITIONS': {
        'Bearer': {'type': 'apiKey', 'in': 'header', 'name': 'Authorization'}
    },
    'PERSIST_AUTH': True,
    'REFETCH_SCHEMA_WITH_AUTH': True,
}

DOCUMENTATION_ENABLED = env.bool('DOCUMENTATION_ENABLED', False)

if env.str('POSTGRES_DB_NAME', ''):
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql_psycopg2',
            'NAME': env.str('POSTGRES_DB_NAME'),
            'USER': env.str('POSTGRES_DB_USER'),
            'PASSWORD': env.str('POSTGRES_DB_PASSWORD'),
            'HOST': env.str('POSTGRES_DB_HOST'),
            'PORT': env.str('POSTGRES_DB_PORT'),
        }
    }
elif ENVIRONMENT == LOCAL_ENVIRONMENT:
    print('Environment is local and POSTGRES_DB_NAME not set, using sqlite db')
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }

ACCESS_TOKEN_LIFETIME = (
    timedelta(minutes=15) if ENVIRONMENT == PROD_ENVIRONMENT else timedelta(days=10)
)
REFRESH_TOKEN_LIFETIME = (
    timedelta(days=15) if ENVIRONMENT == PROD_ENVIRONMENT else timedelta(days=30)
)
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': ACCESS_TOKEN_LIFETIME,
    'REFRESH_TOKEN_LIFETIME': REFRESH_TOKEN_LIFETIME,
    'TOKEN_REFRESH_SERIALIZER': 'authentication.serializers.CustomTokenRefreshSerializer',
    'TOKEN_VERIFY_SERIALIZER': 'authentication.serializers.CustomTokenVerifySerializer',
}

DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'

if env.str('AWS_STORAGE_BUCKET_NAME', ''):
    AWS_ACCESS_KEY_ID = env.str('AWS_ACCESS_KEY_ID')
    AWS_SECRET_ACCESS_KEY = env.str('AWS_SECRET_ACCESS_KEY')
    AWS_STORAGE_BUCKET_NAME = env.str('AWS_STORAGE_BUCKET_NAME')
    AWS_S3_FILE_OVERWRITE = True
    AWS_DEFAULT_ACL = None
    AWS_QUERYSTRING_AUTH = False
    AWS_S3_CUSTOM_DOMAIN = env.str(
        'AWS_S3_CUSTOM_DOMAIN', f'{AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com'
    )

CORS_ORIGIN_WHITELIST = env.list('CORS_ORIGIN_WHITELIST', default=[])

CSRF_TRUSTED_ORIGINS = env.list('CSRF_TRUSTED_ORIGINS', default=[])

FRONTEND_HOST = env.str('FRONTEND_HOST', '')

USE_X_FORWARDED_HOST = True

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Is used for static files in email templates when request is not accessible
STATIC_FILES_HOST = env.str('STATIC_FILES_HOST', '').strip('/')

PARSER_API_LINK = env.str('PARSER_API_LINK', '').strip('/')
PARSER_API_KEY = env.str('PARSER_API_KEY', '')

SERVE_API_LINK = env.str('SERVE_API_LINK', '').strip('/')
SERVE_API_KEY = env.str('SERVE_API_KEY', '')
SERVE_BUCKET_NAME = env.str('SERVE_BUCKET_NAME', '')

GOOGLE_APPLICATION_CREDENTIALS = env.str('GOOGLE_APPLICATION_CREDENTIALS', '')
if env.bool('GCP_LOGGING', False):
    client = Client()
    client.setup_logging()

ALLOWED_EMAILS = env.list('ALLOWED_EMAILS', default=[])

ACCOUNT_EMAIL_SUBJECT_PREFIX = ''

STRIPE_PUBLISHABLE_KEY = env.str('STRIPE_PUBLISHABLE_KEY', '')
STRIPE_SECRET_KEY = env.str('STRIPE_SECRET_KEY', '')
STRIPE_TEST_PUBLIC_KEY = env.str('STRIPE_TEST_PUBLIC_KEY', '')
STRIPE_TEST_SECRET_KEY = env.str('STRIPE_TEST_SECRET_KEY', '')
STRIPE_LIVE_MODE = env.bool('STRIPE_LIVE_MODE', False)
FRONTEND_CHECKOUT_URL = env.str('FRONTEND_CHECKOUT_URL', '')

APP_CONFIG_SUBDOMAIN_TO_SET = env.str('APP_CONFIG_SUBDOMAIN_TO_SET', 'linguana')
APP_CONFIG_ENVIRONMENT = ENVIRONMENT
APP_CONFIG_A_RECORD_IP_SETUP = env.str('APP_CONFIG_A_RECORD_IP_SETUP', '').strip()
APP_CONFIG_WWW_SETUP_URL = env.str('APP_CONFIG_WWW_SETUP_URL', '').strip()
APP_CONFIG_WEBFLOW_SUBDOMAIN_PROXY = env.str(
    'APP_CONFIG_WEBFLOW_SUBDOMAIN_PROXY', 'proxy-ssl.webflow.com'
)
APP_CONFIG_FRAMER_SUBDOMAIN_PROXY = env.str(
    'APP_CONFIG_FRAMER_SUBDOMAIN_PROXY', 'sites.framer.app'
)


USE_GOOGLE_TRANSLATE_FREE_SERVICE = env.bool('USE_GOOGLE_TRANSLATE', False)

MAX_PROJECT_MEDIA_UPLOAD_SIZE_MB = env.int('MAX_PROJECT_MEDIA_UPLOAD_SIZE_MB', 5)

ALLOW_SSL_GENERATION_FOR_DOMAINS = env.list(
    'ALLOW_SSL_GENERATION_FOR_DOMAINS',
    default=['linguana.io', 'linguana.xyz', 'linguana.site'],
)

LINGUANA_PUBLISH_SUBDOMAIN = env.str('LINGUANA_PUBLISH_SUBDOMAIN', '')

AWS_TAKE_SCREENSHOT_LAMBDA = env.str('AWS_TAKE_SCREENSHOT_LAMBDA', '')
AWS_REGION = env.str('AWS_REGION', '')

CHECK_USERS_SUBSCRIPTIONS_LAMBDA_API_KEY = env.str(
    'CHECK_USERS_SUBSCRIPTIONS_LAMBDA_API_KEY', ''
)

CHECK_USERS_FIREBASE_NOTIFICATION_LAMBDA_API_KEY = env.str(
    'CHECK_USERS_FIREBASE_NOTIFICATION_LAMBDA_API_KEY', ''
)

GOOGLE_CLOUD_FUNCTION_API_KEY = env.str('GOOGLE_CLOUD_FUNCTION_API_KEY', '')
BACKGROUND_PROCESS_LIFETIME_IN_MINUTES = env.int(
    'BACKGROUND_PROCESS_LIFETIME_IN_MINUTES', 10
)

# For import_export, the default value is False.
# It determines if the library will use database transactions on data import,
#  just to be on the safe side.
IMPORT_EXPORT_USE_TRANSACTIONS = True

# Firebase real time db url
FCM_API_KEY = env.str('FCM_API_KEY', '')
FIREBASE_REAL_TIME_DB_URL = env.str('FIREBASE_REAL_TIME_DB_URL', '')

MAILER_LITE_TOKEN = env.str('MAILER_LITE_TOKEN', '')
MAILER_LITE_GROUP_ID = env.str('MAILER_LITE_GROUP_ID', '')
