# Generated by Django 4.0.5 on 2023-01-19 18:13

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextTranslation',
            fields=[
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='date updated')),
                ('text', models.TextField()),
                ('ai_translation', models.TextField(blank=True, null=True)),
                ('manual_translation', models.TextField(blank=True, null=True)),
                ('translation_services', models.CharField(choices=[('GOOGLE_CLOUD', 'Google Cloud')], default='GOOGLE_CLOUD', max_length=100)),
                ('text_type', models.CharField(choices=[('TEXT', 'Text'), ('RICH_TEXT', 'Rich Text'), ('ATTRIBUTE', 'Attribute')], default='TEXT', max_length=20)),
                ('attribute_name', models.CharField(blank=True, max_length=100, null=True)),
                ('parsed_element_type', models.CharField(blank=True, max_length=100, null=True)),
                ('is_media_uploaded', models.BooleanField(default=False)),
                ('first_translated_on_page_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='first_translations', to='pages.pagelangversion')),
                ('page_lang_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='pages.pagelangversion')),
            ],
            options={
                'db_table': 'text_translation',
                'unique_together': {('page_lang_version', 'text', 'attribute_name', 'text_type')},
            },
        ),
    ]
