# Generated by Django 4.0.5 on 2023-01-19 19:14

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='texttranslation',
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
