# Generated by Django 4.0.5 on 2023-03-02 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0002_alter_texttranslation_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='texttranslation',
            managers=[
            ],
        ),
    ]
