# Generated by Django 4.0.5 on 2023-08-29 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0003_alter_texttranslation_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='texttranslation',
            name='source',
            field=models.CharField(choices=[('PARSER', 'Parser'), ('CUSTOM', 'Custom')], default='PARSER', max_length=20),
        ),
    ]
